name: 'test-run'
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  feed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - run: npm run release

      - name: usage
        uses: ./
        with:
          url: 'https://note.sarisia.cc/index.xml'
          file: 'README.md'
          start_flag: '<!-- usage start -->'
          end_flag: '<!-- usage end -->'
      - name: examples-qiita
        id: qiita
        uses: ./
        with:
          url: 'https://qiita.com/sarisia/feed'
          file: 'README.md'
          start_flag: "<!-- qiitaex start -->"
          end_flag: "<!-- qiitaex end -->"
      - name: no file but nowrite is set (it's ok)
        uses: ./
        with:
          url: 'https://note.sarisia.cc/index.xml'
          nowrite: true
      - name: mixup
        uses: ./
        with:
          url: |
            https://note.sarisia.cc/index.xml
            https://qiita.com/sarisia/feed
            https://zenn.dev/sarisia/feed
          file: 'README.md'
      - name: empty-feed
        uses: ./
        with:
          url: 'https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/tests/fixture/empty-feed.xml'
          file: 'README.md'
          allow_empty: true

      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: test-run

  must-fail-tests:
    runs-on: ubuntu-latest
    # continue-on-error: true
    steps:
      - uses: actions/checkout@v3.1.0
      - run: npm run release

      - name: nowrite
        uses: ./
        with:
          url: 'https://note.sarisia.cc/index.xml'
          file: 'README.md'
          nowrite: true
      - run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git commit -m "this commit should fail"
        continue-on-error: true
      
      - name: no url
        uses: ./
        continue-on-error: true
        with:
          file: 'README.md'

      - name: no file
        uses: ./
        continue-on-error: true
        with:
          url: 'https://note.sarisia.cc/index.xml'

      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: must file tests

  retry-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - run: npm run release
      - name: retry
        uses: ./
        continue-on-error: true
        with:
          url: 'https://invalid.sarisia.cc/nothing.xml'
          file: 'README.md'
          retry: 2
          retry_backoff: 1
          ensure_all: true